#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Nao Takahashi
# SPDX-License-Identifier: BSD-3-Clause
import sys

n = int(sys.stdin.readline())

a, b = 0, 1
if n == 0:
    print(0)
    sys.exit()
elif n == 1:
    print(1)
    sys.exit()

for _ in range(2, n + 1):
    a, b = b, a + b

print(b)

